language: ruby
rvm:
 - 2.2.2
 - jruby
 - rbx-2

# https://github.com/travis-ci/travis-ci/issues/4090
node_js:
  - "5.5"
  - "4.2"

services:
  - mysql

before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database unsakini_travis'

script:

- bin/rake angular:install

- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake