jwt = require('jsonwebtoken')
tokenSecret = require('../config/jwt_secret')
# Generates a token from supplied payload

module.exports.issue = (payload) ->
  jwt.sign payload, tokenSecret, expiresIn: 180 * 60

# Verifies token on a request

module.exports.verify = (token, callback) ->
  jwt.verify token, tokenSecret, {}, callback

# ---
# generated by js2coffee 2.2.0